import SwiftUI

struct DashboardView: View {
    @EnvironmentObject var store: AppStore
    var body: some View {
        ZStack { ScreenBackground(); ScrollView { VStack(alignment: .leading, spacing: 20) { hero; stats; SectionTitle("Oggi", subtitle: "Le attività della scuola"); today; SectionTitle("Da controllare"); alerts; SectionTitle("Comunicazioni"); announcements }.padding() } }
        .navigationTitle("DanzUp").navigationBarTitleDisplayMode(.inline)
    }
    private var hero: some View { ZStack(alignment: .bottomLeading) { BrandGradient(); Circle().fill(Color.white.opacity(0.12)).frame(width: 180).offset(x: 120, y: -55); VStack(alignment: .leading, spacing: 8) { HStack { Text(store.schoolName).font(.title2.bold()); Spacer(); Image(systemName: "crown.fill") }; Text("Buongiorno, \(store.ownerName)").font(.headline).opacity(0.85); HStack { Label("Piano \(store.selectedPlan.rawValue)", systemImage: "checkmark.seal.fill"); Spacer(); Text("Prova: \(store.trialDaysRemaining) giorni") }.font(.caption.bold()).padding(.top, 8) }.foregroundColor(.white).padding(20) }.frame(height: 175).clipShape(RoundedRectangle(cornerRadius: 28)) }
    private var stats: some View { HStack(spacing: 10) { MiniStat(icon: "person.3.fill", value: "128", label: "Allievi"); MiniStat(icon: "figure.dance", value: "12", label: "Corsi"); MiniStat(icon: "checkmark.circle.fill", value: "91%", label: "Presenze") } }
    private var today: some View { DZCard { VStack(spacing: 14) { ScheduleRow(time: "16:30", title: "Propedeutica", detail: "Sala Étoile • 12 allievi", icon: "sparkles"); Divider(); ScheduleRow(time: "18:30", title: "Hip Hop Teen", detail: "Sala Urban • Marco", icon: "bolt.fill"); Divider(); ScheduleRow(time: "20:00", title: "Latino Avanzato", detail: "Sala Ritmo • Sara", icon: "music.note") } } }
    private var alerts: some View { HStack(spacing: 10) { AlertTile(value: "7", title: "Quote scadute", icon: "eurosign.circle.fill", tint: .red); AlertTile(value: "4", title: "Certificati", icon: "cross.case.fill", tint: .orange) } }
    private var announcements: some View { VStack(spacing: 10) { ForEach(store.announcements.prefix(2)) { item in DZCard { HStack(alignment: .top, spacing: 12) { Image(systemName: "megaphone.fill").foregroundColor(.dzFuchsia); VStack(alignment: .leading, spacing: 4) { Text(item.title).font(.headline); Text(item.body).font(.subheadline).foregroundColor(.secondary); Text(item.audience).font(.caption.bold()).foregroundColor(.dzPurple) }; Spacer() } } } } }
}

private struct MiniStat: View { let icon: String; let value: String; let label: String; var body: some View { VStack(spacing: 7) { Image(systemName: icon).foregroundColor(.dzPurple); Text(value).font(.title3.bold()); Text(label).font(.caption).foregroundColor(.secondary) }.frame(maxWidth: .infinity).padding(.vertical, 15).background(Color(uiColor: .secondarySystemBackground)).clipShape(RoundedRectangle(cornerRadius: 19)) } }
private struct ScheduleRow: View { let time: String; let title: String; let detail: String; let icon: String; var body: some View { HStack(spacing: 13) { Text(time).font(.subheadline.bold()).foregroundColor(.dzPurple).frame(width: 48); Image(systemName: icon).foregroundColor(.white).frame(width: 38, height: 38).background(Color.dzPurple).clipShape(RoundedRectangle(cornerRadius: 12)); VStack(alignment: .leading) { Text(title).font(.headline); Text(detail).font(.caption).foregroundColor(.secondary) }; Spacer(); Image(systemName: "chevron.right").foregroundColor(.secondary) } } }
private struct AlertTile: View { let value: String; let title: String; let icon: String; let tint: Color; var body: some View { HStack { Image(systemName: icon).foregroundColor(tint).font(.title2); VStack(alignment: .leading) { Text(value).font(.title2.bold()); Text(title).font(.caption).foregroundColor(.secondary) }; Spacer() }.padding(15).frame(maxWidth: .infinity).background(tint.opacity(0.09)).clipShape(RoundedRectangle(cornerRadius: 20)) } }
